substitutions:
  # Main prefix for all entities
  name: "Fully Jarvis"
  # Name of your node
  node_name: "fully-jarvis"

esphome:
  name: $node_name
  friendly_name: $name
  platform: ESP8266
  board: d1_mini
  includes:
    - include/JarvisDesk.h
    - src/JarvisDesk.cpp
    - include/HandsetHandler.h
    - src/HandsetHandler.cpp
    - include/ControlboxHandler.h
    - src/ControlboxHandler.cpp
    - include/SerialDevice.h
    - src/SerialDevice.cpp
    - include/SerialMessage.h
    - src/SerialMessage.cpp
    - include/utils.h
    - src/utils.cpp
    - include/Timer.h
    - src/Timer.cpp
  libraries:
    - espsoftwareserial
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_update_password

custom_component:
  lambda: |-
    auto my_custom = new JarvisDesk();
    my_custom->sHeight = id(height_number);
    my_custom->sPreset1 = id(preset_1_sensor);
    my_custom->sPreset2 = id(preset_2_sensor);
    my_custom->sPreset3 = id(preset_3_sensor);
    my_custom->sPreset4 = id(preset_4_sensor);
    my_custom->sSysLimitMin = id(sys_limit_min);
    my_custom->sSysLimitMax = id(sys_limit_max);
    my_custom->sUserLimitMin = id(user_limit_min);
    my_custom->sUserLimitMax = id(user_limit_max);
    my_custom->sUserLimitSet = id(user_limit_set);
    my_custom->sUnits = id(units_select);
    my_custom->sTouchMode = id(touch_mode_select);
    my_custom->sKillMode = id(kill_mode_select);
    my_custom->sSensitivity = id(sensitivity_select);
    return {my_custom};
  components:
    - id: fully_jarvis_desk

binary_sensor:
  - platform: status
    name: "Status"

sensor:
  - platform: template
    name: "Preset 1 Position"
    id: preset_1_sensor
  - platform: template
    name: "Preset 2 Position"
    id: preset_2_sensor
  - platform: template
    name: "Preset 3 Position"
    id: preset_3_sensor
  - platform: template
    name: "Preset 4 Position"
    id: preset_4_sensor
  - platform: template
    name: "User Limit (minimum)"
    id: user_limit_min
  - platform: template
    name: "User Limit (maximum)"
    id: user_limit_max
  - platform: template
    name: "System Limit (minimum)"
    id: sys_limit_min
  - platform: template
    name: "System Limit (maximum)"
    id: sys_limit_max

text_sensor:
  - platform: template
    name: "User Limit"
    id: user_limit_set
  
select:
  - platform: template
    name: "Units"
    id: units_select
    options:
      - inch
      - cm
    optimistic: false
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setUnits(x.c_str());
  - platform: template
    name: "Touch Mode"
    id: touch_mode_select
    options:
      - Continuous
      - Single
    optimistic: false
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setTouchMode(x.c_str());
  - platform: template
    name: "Kill Mode"
    id: kill_mode_select
    options:
      - Kill
      - LetLive
    optimistic: false
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setKillMode(x.c_str());
  - platform: template
    name: "Sensitivity"
    id: sensitivity_select
    options:
      - High
      - Medium
      - Low
    optimistic: false
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setSensitivity(x.c_str());

number:
  - platform: template
    name: "Height"
    id: height_number
    optimistic: false
    min_value: 1
    max_value: 1800
    step: 10
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).move(x*10);
  - platform: template
    name: "Offset"
    id: offset_number
    optimistic: true
    min_value: 1
    max_value: 1800
    step: 1
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setOffset(x);
  - platform: template
    name: "Display Number"
    id: display_number
    optimistic: true
    min_value: 1
    max_value: 1800
    step: 1
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setDisplayNumber(x);

button:
  - platform: template
    name: "Go to Preset 1"
    id: go_preset_1
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).goPreset1();
  - platform: template
    name: "Go to Preset 2"
    id: go_preset_2
    on_press:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).goPreset2();
  - platform: template
    name: "Go to Preset 3"
    id: go_preset_3
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).goPreset3();
  - platform: template
    name: "Go to Preset 4"
    id: go_preset_4
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).goPreset4();
  - platform: template
    name: "Set Preset 1"
    id: set_preset_1
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setPreset1();
  - platform: template
    name: "Set Preset 2"
    id: set_preset_2
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setPreset2();
  - platform: template
    name: "Set Preset 3"
    id: set_preset_3
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setPreset3();
  - platform: template
    name: "Set Preset 4"
    id: set_preset_4
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setPreset4();
  - platform: template
    name: "Set Maximum Height"
    id: set_max_height
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setMaxHeight();
  - platform: template
    name: "Set Minimum Height"
    id: set_min_height
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).setMinHeight();
  - platform: template
    name: "Clear Maximum Height"
    id: clear_max_height
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).clearMaxHeight();
  - platform: template
    name: "Clear Minimum Height"
    id: clear_min_height
    on_press:
      then:
        - lambda: (*reinterpret_cast<JarvisDesk*>(id(fully_jarvis_desk))).clearMinHeight();
